namespace LocalLlmConsole.Models;

/// <summary>
/// Mappings from the launch request and from saved settings onto <see cref="LlamaServerLaunchOptions"/>.
/// Each source type is mapped exactly once here: a field added to the record and to the emitter
/// but missing from these mappings compiles and previews fine, yet silently drops the flag from
/// the launched process, so both mappings are kept side by side to be reviewed together.
/// </summary>
public sealed partial record LlamaServerLaunchOptions
{
    /// <summary>Maps a launch request onto the command-building options.</summary>
    public static LlamaServerLaunchOptions From(RuntimeLaunchRequest request, string host) => new()
    {
        ModelPath = request.ModelPath,
        Host = host,
        Port = request.Port,
        Backend = request.Backend,
        ContextSize = request.ContextSize,
        GpuLayers = request.GpuLayers,
        EnableMetrics = request.EnableMetrics,
        ParallelSlots = request.ParallelSlots,
        BatchSize = request.BatchSize,
        MicroBatchSize = request.MicroBatchSize,
        Threads = request.Threads,
        FlashAttention = request.FlashAttention,
        CacheTypeK = request.CacheTypeK,
        CacheTypeV = request.CacheTypeV,
        KvOffload = request.KvOffload,
        KvUnified = request.KvUnified,
        PromptCacheMode = request.PromptCacheMode,
        PromptCacheRamMb = request.PromptCacheRamMb,
        ContextCheckpointsMode = request.ContextCheckpointsMode,
        ContextCheckpointCount = request.ContextCheckpointCount,
        ContextCheckpointEveryNTokens = request.ContextCheckpointEveryNTokens,
        ContinuousBatching = request.ContinuousBatching,
        ReasoningMode = request.ReasoningMode,
        ReasoningFormat = request.ReasoningFormat,
        ReasoningBudget = request.ReasoningBudget,
        JinjaMode = request.JinjaMode,
        VisionMode = request.VisionMode,
        VisionProjectorPath = request.VisionProjectorPath,
        VisionProjectorEmbedded = request.VisionProjectorEmbedded,
        VisionImageMinTokens = request.VisionImageMinTokens,
        VisionImageMaxTokens = request.VisionImageMaxTokens,
        MmapMode = request.MmapMode,
        MlockMode = request.MlockMode,
        Temperature = request.Temperature,
        TopK = request.TopK,
        TopP = request.TopP,
        MinP = request.MinP,
        MaxTokens = request.MaxTokens,
        Seed = request.Seed,
        RepeatLastN = request.RepeatLastN,
        RepeatPenalty = request.RepeatPenalty,
        PresencePenalty = request.PresencePenalty,
        FrequencyPenalty = request.FrequencyPenalty,
        RopeScaling = request.RopeScaling,
        RopeScale = request.RopeScale,
        RopeFreqBase = request.RopeFreqBase,
        RopeFreqScale = request.RopeFreqScale,
        SpeculativeType = request.SpeculativeType,
        SpecDraftModelPath = request.SpecDraftModelPath,
        MtpHeadPath = request.MtpHeadPath,
        SpecDraftGpuLayers = request.SpecDraftGpuLayers,
        SpecDraftMinTokens = request.SpecDraftMinTokens,
        SpecDraftMaxTokens = request.SpecDraftMaxTokens,
        SpecDraftPSplit = request.SpecDraftPSplit,
        SpecDraftPMin = request.SpecDraftPMin,
        SpecDraftCacheTypeK = request.SpecDraftCacheTypeK,
        SpecDraftCacheTypeV = request.SpecDraftCacheTypeV,
        FlagValues = request.FlagValues,
        SupportedFlags = request.SupportedFlags
    };

    /// <summary>
    /// Maps saved settings onto the command-building options for the command preview. The model
    /// path and host are placeholders because the preview is model-independent, and
    /// SupportedFlags is left null so the preview shows the full command the user asked for.
    /// </summary>
    public static LlamaServerLaunchOptions From(AppSettings settings, RuntimeBackend backend, IReadOnlyList<string>? flagOrder = null) => new()
    {
        ModelPath = "",
        Host = "127.0.0.1",
        Port = settings.Port,
        Backend = backend,
        ContextSize = settings.ContextSize,
        GpuLayers = settings.GpuLayers,
        EnableMetrics = settings.EnableMetrics,
        ParallelSlots = settings.ParallelSlots,
        BatchSize = settings.BatchSize,
        MicroBatchSize = settings.MicroBatchSize,
        Threads = settings.Threads,
        FlashAttention = settings.FlashAttention,
        CacheTypeK = settings.CacheTypeK,
        CacheTypeV = settings.CacheTypeV,
        KvOffload = settings.KvOffload,
        KvUnified = settings.KvUnified,
        PromptCacheMode = settings.PromptCacheMode,
        PromptCacheRamMb = settings.PromptCacheRamMb,
        ContextCheckpointsMode = settings.ContextCheckpointsMode,
        ContextCheckpointCount = settings.ContextCheckpointCount,
        ContextCheckpointEveryNTokens = settings.ContextCheckpointEveryNTokens,
        ContinuousBatching = settings.ContinuousBatching,
        ReasoningMode = settings.ReasoningMode,
        ReasoningFormat = settings.ReasoningFormat,
        ReasoningBudget = settings.ReasoningBudget,
        JinjaMode = settings.JinjaMode,
        VisionMode = settings.VisionMode,
        VisionProjectorPath = settings.VisionProjectorPath,
        VisionProjectorEmbedded = false,
        VisionImageMinTokens = settings.VisionImageMinTokens,
        VisionImageMaxTokens = settings.VisionImageMaxTokens,
        MmapMode = settings.MmapMode,
        MlockMode = settings.MlockMode,
        Temperature = settings.Temperature,
        TopK = settings.TopK,
        TopP = settings.TopP,
        MinP = settings.MinP,
        MaxTokens = settings.MaxTokens,
        Seed = settings.Seed,
        RepeatLastN = settings.RepeatLastN,
        RepeatPenalty = settings.RepeatPenalty,
        PresencePenalty = settings.PresencePenalty,
        FrequencyPenalty = settings.FrequencyPenalty,
        RopeScaling = settings.RopeScaling,
        RopeScale = settings.RopeScale,
        RopeFreqBase = settings.RopeFreqBase,
        RopeFreqScale = settings.RopeFreqScale,
        SpeculativeType = settings.SpeculativeType,
        SpecDraftModelPath = settings.SpecDraftModelPath,
        MtpHeadPath = settings.MtpHeadPath,
        SpecDraftGpuLayers = settings.SpecDraftGpuLayers,
        SpecDraftMinTokens = settings.SpecDraftMinTokens,
        SpecDraftMaxTokens = settings.SpecDraftMaxTokens,
        SpecDraftPSplit = settings.SpecDraftPSplit,
        SpecDraftPMin = settings.SpecDraftPMin,
        SpecDraftCacheTypeK = settings.SpecDraftCacheTypeK,
        SpecDraftCacheTypeV = settings.SpecDraftCacheTypeV,
        FlagValues = settings.FlagValues,
        FlagOrder = flagOrder
    };
}
